<?php
$auto_reviews_ship = array(
    array("name" => "Damir H.", "text" => "Nisam morao dugo čekati, isporuka odrađena profesionalno."),
    array("name" => "Vjeko M.", "text" => "Dostava je bila iznimno brza, a sve informacije sam dobio na mail i SMS. Posebno mi se svidjelo što je kurir nazvao prije dolaska. Osjećao sam se kao da je sve organizirano baš po mjeri kupca."),
    array("name" => "Stanko P.", "text" => "Sve stiglo na vrijeme, kurir vrlo ljubazan."),
    array("name" => "Nikola V.", "text" => "Pakiranje zaista kvalitetno, vidi se trud."),
    array("name" => "Mato K.", "text" => "Paket je stigao neoštećen i odlično zapakiran. Sve je bilo zaštićeno tako da nema šanse da se nešto ošteti u transportu. Velike pohvale za profesionalnost."),
    array("name" => "Marko C.", "text" => "Usluga dostave bez greške."),
    array("name" => "Leon T.", "text" => "Dostavljač je bio pristojan i ljubazan, a isporuka točna u minutu. Paket je bio uredno složen i bez ikakvih oštećenja. Jako sam zadovoljan."),
    array("name" => "Žarko T.", "text" => "Vrlo brza isporuka i odlična koordinacija."),
    array("name" => "Branimir S.", "text" => "Usluga na visokoj razini, sve jasno."),
    array("name" => "Kristijan O.", "text" => "Pakiranje je bilo vrlo uredno i sigurno. Nije bilo nikakvih oštećenja, a dostava je stigla na dogovoreni termin. Od mene samo pohvale."),
    array("name" => "Zdravko J.", "text" => "Uredno zapakirano i sigurno dostavljeno."),
    array("name" => "Tomislav R.", "text" => "Paket stigao ranije od roka."),
    array("name" => "Ivan B.", "text" => "Sve stiglo ranije nego što sam očekivao."),
    array("name" => "Domagoj C.", "text" => "Dostava bila točna i brza."),
    array("name" => "Zdravko U.", "text" => "Dostava je bila brza, a pakiranje vrlo uredno. Podrška je bila dostupna i izvan radnog vremena. Preporučujem svakome tko želi bezbrižnu kupnju."),
    array("name" => "Mladen C.", "text" => "Ambalaža uredna i kvalitetna."),
    array("name" => "Željko R.", "text" => "Korisnička podrška je brzo odgovorila na moj upit o roku dostave. Paket je stigao čak i ranije nego što je pisalo na stranici. Za svaku preporuku."),
    array("name" => "Saša L.", "text" => "Vrlo jednostavan postupak preuzimanja."),
    array("name" => "Tomislav P.", "text" => "Brza dostava i jednostavno preuzimanje."),
    array("name" => "Dario S.", "text" => "Jako dobra usluga."),
    array("name" => "Siniša H.", "text" => "Od trenutka narudžbe do isporuke sve je prošlo glatko. Uvijek sam imao uvid u status pošiljke i to mi je ulilo povjerenje. Vrlo kvalitetna usluga."),
    array("name" => "Petar V.", "text" => "Dostava bila brza."),
    array("name" => "Filip P.", "text" => "Paket je stigao u roku od 2 dana, što me jako iznenadilo. Pakiranje je bilo kvalitetno i uredno, baš kako treba. Definitivno ću ponovno naručivati."),
    array("name" => "Ante F.", "text" => "Sve prošlo glatko."),
    array("name" => "Mario D.", "text" => "Paket stigao ranije od predviđenog roka."),
    array("name" => "Nikola J.", "text" => "Paket stigao neoštećen."),
    array("name" => "Blaž I.", "text" => "Naručivanje je bilo jednostavno, a dostava još jednostavnija. Sve informacije o praćenju bile su jasne i ažurne. Top usluga."),
    array("name" => "Ivan K.", "text" => "Nema zamjerke."),
    array("name" => "Dino A.", "text" => "Pratio sam dostavu online i sve je funkcioniralo besprijekorno. Paket je stigao ranije i uredno zapakiran. Svi detalji bili su dostupni na vrijeme."),
    array("name" => "Hrvoje M.", "text" => "Sve informacije o praćenju sam dobio odmah."),
    array("name" => "Bojan R.", "text" => "Pakiranje uredno, stiglo sigurno i neoštećeno."),
    array("name" => "Andrej Z.", "text" => "Dostava bila brža nego što piše."),
    array("name" => "Darko G.", "text" => "Podrška uvijek dostupna."),
    array("name" => "Vlado F.", "text" => "Nisam imao nikakvih poteškoća, sve glatko."),
    array("name" => "Ivan Z.", "text" => "Korisnička podrška je bila vrlo susretljiva i brzo mi odgovorila. Dostava je stigla ranije nego što je pisalo u obavijesti. Sve preporuke."),
    array("name" => "Alen V.", "text" => "Jako zadovoljan."),
    array("name" => "Miro B.", "text" => "Vrlo brza dostava."),
    array("name" => "Josip G.", "text" => "Uredno zapakirano i brzo isporučeno."),
    array("name" => "Hrvoje D.", "text" => "Nakon narudžbe sve je išlo jako brzo. Paket je bio spreman i poslan isti dan, a stigao već sutradan. Odlično iskustvo."),
    array("name" => "Nino T.", "text" => "Brza obrada narudžbe, odlično."),
    array("name" => "Ante H.", "text" => "Rijetko se vidi ovako profesionalna usluga."),
    array("name" => "Goran J.", "text" => "Naručio sam u ponedjeljak, a paket je stigao već u srijedu. Cijeli proces je bio jednostavan i pregledan. Jako sam zadovoljan."),
    array("name" => "Nikola T.", "text" => "Dostava je bila brža nego što sam očekivao. Dobio sam obavijest u svakoj fazi, što mi je ulilo povjerenje. Vrlo profesionalna usluga."),
    array("name" => "Alen F.", "text" => "Paket stigao ranije."),
    array("name" => "Marko Z.", "text" => "Cijeli proces dostave bio je jednostavan."),
    array("name" => "Ivan L.", "text" => "Odmah nakon narudžbe dobio sam potvrdu i broj za praćenje paketa. Paket je stigao neoštećen i na vrijeme. Usluga zaslužuje čistu peticu."),
    array("name" => "Kristijan N.", "text" => "Paket stigao u savršenom stanju."),
    array("name" => "Marijan D.", "text" => "Imam samo riječi hvale – od narudžbe do dostave sve je bilo odrađeno profesionalno. Kurir me nazvao prije isporuke i sve je prošlo bez stresa. Svaka čast."),
    array("name" => "Matej R.", "text" => "Praćenje dostave radilo odlično."),
    array("name" => "Petar L.", "text" => "Paket stigao uredno zapakiran i brzo isporučen."),
    array("name" => "Luka F.", "text" => "Sve je prošlo bez stresa – narudžba, potvrda i dostava. Paket je bio sigurno zapakiran i stigao na vrijeme. Top usluga."),
    array("name" => "Željko O.", "text" => "Sve prošlo glatko i brzo."),
    array("name" => "Mario E.", "text" => "Cijenim što je dostavljač bio pristojan i nazvao prije dolaska. Nisam morao gubiti vrijeme, sve je bilo dogovoreno unaprijed. Vrlo ugodno iskustvo."),
    array("name" => "Renato K.", "text" => "Dostavljač bio vrlo susretljiv."),
    array("name" => "Nikša B.", "text" => "Sve prošlo glatko i uredno."),
    array("name" => "Zoran J.", "text" => "Pohvale za korisničku podršku, brzo riješili upit."),
    array("name" => "Davor L.", "text" => "Kurir nazvao prije isporuke, odlična organizacija."),
    array("name" => "Damir R.", "text" => "Dostavljač je bio ljubazan i profesionalan. Paket je stigao bez ikakvih problema. Vrlo pozitivno iskustvo."),
    array("name" => "Stjepan H.", "text" => "Kurir bio susretljiv."),
    array("name" => "Vjekoslav D.", "text" => "Dostava brza i uredna."),
    array("name" => "Marijan K.", "text" => "Dostava je bila brza i uredna, paket bez oštećenja."),
    array("name" => "Boris I.", "text" => "Usluga dostave odlična."),
    array("name" => "Ante V.", "text" => "Paket je stigao uredno zapakiran i bez oštećenja. Ambalaža je bila čvrsta i kvalitetna. Vidjelo se da se pazi na detalje."),
    array("name" => "Stjepan P.", "text" => "Dostavljač me kontaktirao prije isporuke."),
    array("name" => "Ivan J.", "text" => "Uredno zapakirano, sve pohvale."),
    array("name" => "Damjan E.", "text" => "Sve pohvale na brzini i točnosti."),
    array("name" => "Darko O.", "text" => "Sve prošlo točno kako je navedeno."),
    array("name" => "Nikola H.", "text" => "Sve uredno i točno."),
    array("name" => "Blaž P.", "text" => "Sve pohvale."),
    array("name" => "Sven K.", "text" => "Sve odlično."),
    array("name" => "Goran F.", "text" => "Kurir bio točan i ljubazan."),
    array("name" => "Tomislav Z.", "text" => "Sve bilo odlično."),
    array("name" => "Mario J.", "text" => "Nisam morao čekati dugo."),
    array("name" => "Slaven J.", "text" => "Cijeli postupak narudžbe i dostave bio je ugodan."),
    array("name" => "Mate C.", "text" => "Dostava super."),
    array("name" => "Kristijan E.", "text" => "Dostava uredna."),
    array("name" => "Ivan M.", "text" => "Sve bilo transparentno i jasno."),
    array("name" => "Luka B.", "text" => "Sve informacije bile dostupne."),
    array("name" => "Josip D.", "text" => "Sve informacije o dostavi bile jasne."),
    array("name" => "Nenad B.", "text" => "Pakiranje čvrsto i sigurno, svaka pohvala."),
    array("name" => "Mislav R.", "text" => "Stiglo brzo."),
    array("name" => "Saša D.", "text" => "Kurir bio vrlo korektan."),
    array("name" => "Leon M.", "text" => "Sve stiglo uredno i na vrijeme."),
    array("name" => "Željko M.", "text" => "Paket stigao na vrijeme."),
    array("name" => "Kristijan V.", "text" => "Ambalaža kvalitetna, paket neoštećen."),
    array("name" => "Lovro N.", "text" => "Sve pohvale za uslugu."),
    array("name" => "Alen K.", "text" => "Kurir bio jako profesionalan."),
    array("name" => "Ivan T.", "text" => "Ambalaža jako kvalitetna."),
    array("name" => "Ante G.", "text" => "Pakiranje čvrsto."),
    array("name" => "Marin G.", "text" => "Odlična komunikacija s podrškom."),
    array("name" => "Davor O.", "text" => "Dostava bila izuzetno brza."),
    array("name" => "Robert E.", "text" => "Pakiranje uredno i čvrsto."),
    array("name" => "Filip M.", "text" => "Sve prošlo jednostavno i bez komplikacija."),
    array("name" => "Ante I.", "text" => "Nakon narudžbe odmah sam dobio sve potrebne podatke za praćenje. Dostava je bila točna i uredna. Odlična organizacija."),
    array("name" => "Marko P.", "text" => "Dostava brza, sve uredno složeno i zapakirano."),
    array("name" => "Zdravko K.", "text" => "Cijeli proces dostave bio je vrlo transparentan. Dobio sam obavijesti o svakoj fazi. Nema stresa, sve funkcionira odlično."),
    array("name" => "Srećko G.", "text" => "Usluga odlična, dostavljač bio vrlo profesionalan."),
    array("name" => "Bruno Z.", "text" => "Sve stiglo točno na vrijeme."),
    array("name" => "Slaven P.", "text" => "Sve što se tiče dostave prošlo je glatko. Kurir je bio ljubazan i točan, a paket uredno zapakiran. Jako sam zadovoljan."),
    array("name" => "Luka J.", "text" => "Dostava brza, kurir ljubazan i paket uredan."),
    array("name" => "Mislav S.", "text" => "Dostavljač bio jako ljubazan."),
    array("name" => "Ante K.", "text" => "Sve faze dostave bile su uredno komunicirane. Paket je stigao ranije i bio je dobro zapakiran. Vrlo pozitivno iskustvo."),
    array("name" => "Domagoj N.", "text" => "Podrška dostupna i vikendom, sve pohvale."),
    array("name" => "Filip K.", "text" => "Praćenje pošiljke radilo savršeno."),
    array("name" => "Luka C.", "text" => "Sve jasno i uredno, stiglo bez kašnjenja."),
    array("name" => "Karlo P.", "text" => "Vrlo jednostavno preuzimanje."),
    array("name" => "Vjekoslav C.", "text" => "Brza i pouzdana dostava."),
    array("name" => "Damir V.", "text" => "Sve prošlo bez ikakvih problema."),
    array("name" => "Ante I.", "text" => "Dostava je bila odrađena besprijekorno. Kurir je bio vrlo ljubazan i nazvao prije dolaska. Sve pohvale za cijeli tim."),
    array("name" => "Lovro C.", "text" => "Sve stiglo bez kašnjenja."),
    array("name" => "Robert N.", "text" => "Podrška me obavještavala o svemu."),
    array("name" => "Željko E.", "text" => "Obično sam skeptičan prema recenzijama, ali ovdje je sve točno."),
    array("name" => "Siniša T.", "text" => "Nisam imao nikakvih problema."),
    array("name" => "Mario L.", "text" => "Paket stigao neoštećen i uredan."),
    array("name" => "Andro P.", "text" => "Sve prošlo jednostavno i brzo. Dostava na vrijeme i bez problema. Definitivno preporučujem."),
    array("name" => "Lovro N.", "text" => "Sve pohvale za uslugu."),
    array("name" => "Mislav K.", "text" => "Dostava bila vrlo brza, a kurir pristojan. Paket je stigao u odličnom stanju. Sve preporuke."),
    array("name" => "Toni H.", "text" => "Vrlo jednostavan proces narudžbe."),
    array("name" => "Vedran R.", "text" => "Nisam čekao dugo, sve stiglo brzo."),
    array("name" => "Marijan L.", "text" => "Sve bilo brzo i jednostavno. Paket uredan, dostava brza i sigurna. Vrlo pozitivno iskustvo."),
    array("name" => "Mislav S.", "text" => "Dostavljač bio jako ljubazan."),

);
?>
