<?php
$auto_reviews_en = array(
    array("name" => "Zvonko E.", "text" => "Boja ostaje postojana i nakon puno pranja."),
    array("name" => "Marijan H.", "text" => "Noriks majica me stvarno iznenadila. Tkanina je glatka na koži, a rez prati liniju tijela bez stezanja. Nakon cijelog dana nošenja osjećaj je i dalje svjež."),
    array("name" => "Tin V.", "text" => "Izgleda moderno i luksuzno, iako je cijena pristupačna."),
    array("name" => "Deni B.", "text" => "Nosim je svaki dan."),
    array("name" => "Kristijan L.", "text" => "Nisam bio siguran na početku, ali nadmašila je moja očekivanja. Kupit ću još jednu."),
    array("name" => "Vjeko I.", "text" => "Minimalistički dizajn, kombinira se sa svime."),
    array("name" => "Hrvoje S.", "text" => "Nakon desetak pranja ista kao nova."),
    array("name" => "Nikša H.", "text" => "Ne vidi se znoj."),
    array("name" => "Marko U.", "text" => "Pristaje i vitkima i snažnijima."),
    array("name" => "Andro P.", "text" => "Noriks mi je postao standard za svaki dan. Mekana je, ali čvrsta i ne gubi formu. Veličina odgovara tablici, nema iznenađenja."),
    array("name" => "Matija K.", "text" => "Tkanina je lagana, ali neprozirna."),
    array("name" => "Dario Z.", "text" => "Vrlo udobna majica. Već sam naručio još jednu. Paše uz gotovo sve."),
    array("name" => "Lovro I.", "text" => "Ide na sve boje."),
    array("name" => "Ivan L.", "text" => "Dovoljno duga da ostane u hlačama."),
    array("name" => "Blaž H.", "text" => "Tkanina ne grebe kožu i majica ne iritira ni tijekom znojenja."),
    array("name" => "Toni J.", "text" => "Za sport i za grad."),
    array("name" => "Zoran G.", "text" => "Mekan, a izdržljiv materijal."),
    array("name" => "Stjepan T.", "text" => "Na prvu se vidi da nije jeftina."),
    array("name" => "Boris C.", "text" => "Jednostavna, ali izgleda moderno."),
    array("name" => "Danijel P.", "text" => "Dobio sam više nego što sam očekivao."),
    array("name" => "Mislav U.", "text" => "Nosio sam je na putovanju – nije se izgužvala ni nakon sati u koferu."),
    array("name" => "Ivan R.", "text" => "Super lagana i udobna."),
    array("name" => "Tomislav L.", "text" => "Nosim je i uz sako i uz trenirku."),
    array("name" => "Nikola O.", "text" => "Trajna boja."),
    array("name" => "Marko E.", "text" => "Imam ih već pet."),
    array("name" => "Goran T.", "text" => "Ima izgled i funkcionalnost."),
    array("name" => "Mario M.", "text" => "Osjeća se premium već na dodir."),
    array("name" => "Robert L.", "text" => "Izgleda muževno i sofisticirano."),
    array("name" => "Ante J.", "text" => "Nosim je gotovo svaki drugi dan – ne izlazi iz rotacije."),
    array("name" => "Nikola T.", "text" => "Mekana poput pamuka, a izdržljivija."),
    array("name" => "Alen M.", "text" => "Materijal je mekan, ali se ne razvlači ni nakon nekoliko pranja. Svaka čast!"),
    array("name" => "Filip P.", "text" => "Noriks me kupio već na prvo nošenje. Prozračna je i ne lijepi se uz kožu. Kroj izgleda uredno i na traperice i na chino."),
    array("name" => "Bruno L.", "text" => "Prava duljina rukava."),
    array("name" => "Gordan F.", "text" => "Dugo sam tražio ovakav model. Hvala što postojite!"),
    array("name" => "Kristijan B.", "text" => "Vrlo otporna na habanje – već sam je nosio više puta, izgleda kao nova."),
    array("name" => "Tomislav T.", "text" => "Luksuzna na dodir."),
    array("name" => "Petar N.", "text" => "Odlično izgleda s jaknom."),
    array("name" => "Damir V.", "text" => "Oprao sam ju već nekoliko puta i nema znakova habanja ili izbljeđivanja. Drago mi je da sam pronašao majicu koja stvarno traje. Kupit ću još jednu."),
    array("name" => "Igor N.", "text" => "Ne gužva se ni nakon cijelog dana."),
    array("name" => "Nenad U.", "text" => "Boja izgleda još bolje uživo. Bogata, duboka i moderna."),
    array("name" => "Sven Z.", "text" => "Tkanina se brzo pegla."),
    array("name" => "Zdravko Z.", "text" => "Oduševljen sam! Pogodila je sve što sam tražio."),
    array("name" => "Adrian L.", "text" => "Paše uz sve hlače."),
    array("name" => "Ante F.", "text" => "Pristaje iako sam između veličina."),
    array("name" => "Ivan K.", "text" => "Savršena veličina."),
    array("name" => "Željko G.", "text" => "Prava majica za modernog muškarca – ništa previše, sve taman."),
    array("name" => "Dino M.", "text" => "Klasika s daškom stila."),
    array("name" => "Hrvoje A.", "text" => "Lagani sportski štih s elegantnim završetkom – odlična kombinacija."),
    array("name" => "Mario H.", "text" => "Za ured i slobodno vrijeme."),
    array("name" => "Luka I.", "text" => "Nema zatezanja ni ispod pazuha."),
    array("name" => "Ivan M.", "text" => "Kroj savršen iako sam visok."),
    array("name" => "Stipe K.", "text" => "Pronašao sam novu omiljenu."),
    array("name" => "Bojan S.", "text" => "Idealna za putovanja – lagana i kompaktna."),
    array("name" => "Franjo C.", "text" => "Nosio sam je na intervju – osjećao sam se samouvjereno."),
    array("name" => "Tomo H.", "text" => "Savršena dužina i kroj."),
    array("name" => "Nikola G.", "text" => "Nosim je na posao i u grad."),
    array("name" => "Vlado G.", "text" => "Elegantna i udobna."),
    array("name" => "Josip L.", "text" => "Savršen balans između elegancije i udobnosti."),
    array("name" => "Luka T.", "text" => "Odlična za treninge i svakodnevno nošenje. Prozračna i čvrsta."),
    array("name" => "Ivan J.", "text" => "Kvaliteta iznad cijene."),
    array("name" => "Leon Z.", "text" => "Zadržava oblik i boju."),
    array("name" => "Blaž E.", "text" => "Može se lako složiti za formalniji izgled. Svestrana stvar."),
    array("name" => "Marko T.", "text" => "Dobio sam puno komplimenata."),
    array("name" => "Kristijan H.", "text" => "Ne ostavlja dlačice."),
    array("name" => "Tihomir V.", "text" => "Drži se cijeli dan."),
    array("name" => "Filip Z.", "text" => "Majica za svaku priliku."),
    array("name" => "Dražen V.", "text" => "Udobna cijeli dan."),
    array("name" => "Mirko D.", "text" => "Minimalistički i muževan dizajn."),
    array("name" => "Saša O.", "text" => "Funkcionira za svaki dan."),
    array("name" => "Robert G.", "text" => "Najbolje što sam kupio online."),
    array("name" => "Ante G.", "text" => "Moja prva opcija svako jutro."),
    array("name" => "Damir L.", "text" => "Pristaje kao salivena."),
    array("name" => "Kristijan V.", "text" => "Kroj Noriks majice je stvarno pogođen. Prati liniju, ali ne steže ni u ramenima ni oko struka. I nakon pranja se ne uvija."),
    array("name" => "Alen W.", "text" => "Majica koja izgleda i skuplje nego što stvarno jest."),
    array("name" => "Emil W.", "text" => "Izgleda skuplje nego što jest."),
    array("name" => "Vjekoslav U.", "text" => "Tkanina je mekana, ali ne pokazuje tragove nošenja. Izvrsna."),
    array("name" => "Tihomir E.", "text" => "Rukavi nisu preuski."),
    array("name" => "Petar M.", "text" => "Dugo nisam bio ovako zadovoljan nekom 'običnom' majicom."),
    array("name" => "Domagoj T.", "text" => "Za šetnje i izlaske."),
    array("name" => "Bruno K.", "text" => "Ne deformira se."),
    array("name" => "Ante I.", "text" => "Noriks mi je najugodnija majica ove sezone. Ne lijepi se, diše i ne žulja ni oko šavova. Odlično stoji i u casual i u smart kombinacijama."),
    array("name" => "Siniša P.", "text" => "Jedva čekam da se osuši."),
    array("name" => "Karlo U.", "text" => "Casual stil koji volim."),
    array("name" => "Nikša Z.", "text" => "Odličan omjer cijene i kvalitete. Teško je naći ovako nešto u trgovinama."),
    array("name" => "Fabijan R.", "text" => "Ne gužva se lako, što mi je super jer ne volim peglanje."),
    array("name" => "Zlatko F.", "text" => "Napokon nešto moderno što ne žrtvuje udobnost."),
    array("name" => "Marko P.", "text" => "Noriks izgleda uredno i kad se nosi cijeli dan. Tkanina je dovoljno rastezljiva da ne sputava pokret. Top preporuka."),
    array("name" => "Josip X.", "text" => "Lagana za ljeto, slojevita za jesen."),
    array("name" => "Vladimir K.", "text" => "Postala mi je omiljena."),
    array("name" => "Erik J.", "text" => "Izgleda čak bolje uživo nego na slikama. Preporučujem!"),
    array("name" => "Tomislav S.", "text" => "Poseban izgled i osjećaj."),
    array("name" => "Karlo Z.", "text" => "Jednako dobra ispod pulovera."),
    array("name" => "Zvonimir N.", "text" => "Ne klizi s ramena."),
    array("name" => "Ivan D.", "text" => "Udobna i profesionalna."),
    array("name" => "Nino G.", "text" => "Majica ostaje svježa čak i nakon cijelog dana u pokretu."),
    array("name" => "Lovro M.", "text" => "Konačno majica koja odgovara i višim osobama poput mene."),
    array("name" => "Boris T.", "text" => "Toliko udobna da je kao pidžama."),
    array("name" => "Filip K.", "text" => "Odlična dužina – ne podiže se i ne sklizne iz hlača."),
    array("name" => "Tomislav J.", "text" => "Brzo se suši, odlično za putovanja."),
    array("name" => "Stjepan M.", "text" => "Ne izgleda samo odlično, nego se i osjeća kao da ništa ne nosim."),
    array("name" => "Goran V.", "text" => "Ako tražite nešto pouzdano i kvalitetno – evo vam rješenja."),
    array("name" => "Davor I.", "text" => "Praktična i moderna – što više poželjeti?"),
    array("name" => "Željko B.", "text" => "Uz ovu majicu svaki outfit izgleda dotjeranije."),
    array("name" => "Neven D.", "text" => "Majica je dobila pet od pet od moje djevojke – vrijedi!"),
    array("name" => "Vedran G.", "text" => "Svaki put kad je operem, brzo se osuši i izgleda kao nova."),
    array("name" => "Ivan Z.", "text" => "Ova majica mi je postala dio svakodnevnog outfita."),
    array("name" => "Kristijan D.", "text" => "Savršen balans između sportskog i elegantnog."),
    array("name" => "Mislav R.", "text" => "Noriks mi je u rotaciji svaki tjedan. Drži formu i boju, a rez je taman – ni preširok ni preuzak. Vrijedi svake kune."),
    array("name" => "Mate V.", "text" => "Drago mi je što kroj ne visi ni oko struka ni u ramenima."),
    array("name" => "Filip F.", "text" => "Ne mijenja oblik nakon pranja."),
    array("name" => "Alen C.", "text" => "Boja je ostala postojana i nakon puno ciklusa u perilici."),
    array("name" => "Kristijan P.", "text" => "Kroj prati liniju tijela, ali nije neudoban – baš kako treba."),
    array("name" => "Blaž K.", "text" => "Dobro pristaje čak i osobama s jačim gornjim dijelom tijela."),
    array("name" => "Tomislav G.", "text" => "Otporna i nakon sporta."),
    array("name" => "Andrej N.", "text" => "Majica savršeno diše i ugodna je čak i tijekom napornih dana u uredu."),
    array("name" => "Ante K.", "text" => "Noriks me stvarno zadovoljio. Materijal djeluje kvalitetno i ne presijava se ružno. Lako se kombinira s bilo čime."),
    array("name" => "Saša R.", "text" => "Prošla test 12 sati na poslu."),
    array("name" => "Ivan N.", "text" => "Tražio sam ovakvu majicu godinama."),
    array("name" => "Domagoj R.", "text" => "Uz ovu majicu sve ide."),
    array("name" => "Luka W.", "text" => "Super alternativa košulji."),
    array("name" => "Emil T.", "text" => "Odlično rješenje za svaki dan – ne razmišljam više što obući."),
    array("name" => "Robert N.", "text" => "Noriks drži standard i nakon mjesec dana pranja. Šavovi uredni, rubovi se ne uvijaju. Stoji kao prvog dana."),
    array("name" => "Marko Q.", "text" => "I nakon cjelodnevnog nošenja nema zatezanja ni neugode."),
    array("name" => "Kristijan J.", "text" => "Odlična i poslovno i casual."),
    array("name" => "Josip E.", "text" => "Pristaje kao salivena."),
    array("name" => "Željko F.", "text" => "Čak i nakon višestrukog nošenja izgleda kao nova."),
    array("name" => "Dario W.", "text" => "Udobna u svim položajima."),
    array("name" => "Luka B.", "text" => "Svaki dan je nosim."),
    array("name" => "Krešo D.", "text" => "Izgleda kao skrojena."),
    array("name" => "Siniša G.", "text" => "Super se ponaša i kod znojenja – ne ostaju ružni tragovi."),
    array("name" => "Branimir V.", "text" => "Super mi je što se majica ne rasteže nakon pranja."),
    array("name" => "Damjan S.", "text" => "Odlična majica za slojevito odijevanje. Funkcionira s košuljom ili jaknom."),
    array("name" => "Ante V.", "text" => "Svježina ostaje cijeli dan."),
    array("name" => "Toni L.", "text" => "Ugodna i na suncu."),
    array("name" => "Nikola L.", "text" => "Dobio puno komplimenata."),
    array("name" => "Boris M.", "text" => "Rijetko pišem recenzije, ali ovdje sam morao – oduševljen sam."),
    array("name" => "Marijan K.", "text" => "Noriks se lako pere i brzo suši. Čak i bez pegle izgleda uredno. Zaista praktično za svaki dan."),
    array("name" => "Goran S.", "text" => "Detalji oko vrata su stvarno lijepo izrađeni. Kvaliteta se vidi."),
    array("name" => "Ivan Z.", "text" => "Dio svakodnevnog outfita."),
    array("name" => "Bruno G.", "text" => "Djeluje kao da traje godinama, a nosi se kao nova svaki put."),
    array("name" => "Vjekoslav C.", "text" => "Noriks kroj skriva sitne nedostatke i laska figuri. Tkanina je dovoljno gusta da ne prozire. Jako zadovoljan."),
    array("name" => "Filip O.", "text" => "Usluga odlična."), /* (kratko, ali o proizvodu već ima dosta — ostavljamo raznolikost) */
    array("name" => "Zdenko D.", "text" => "Kupio sam jednu i odmah naručio još tri različite boje. Odličan izbor."),
    array("name" => "Tomislav P.", "text" => "Ugodna i nakon cijelog dana."),
    array("name" => "Stjepan P.", "text" => "Dovoljno rastezljiva."),
    array("name" => "Mislav S.", "text" => "Noriks izgleda uredno i nakon pranja. Šavovi su ravni, a ovratnik ne gubi formu. Vrlo kvalitetna izrada."),
    array("name" => "Viktor I.", "text" => "Ne lijepi se ni kad se oznojim."),
    array("name" => "Ante R.", "text" => "Jednostavno – ništa za dodati, ništa za oduzeti. Savršena."),
    array("name" => "Lovro R.", "text" => "Najugodnija majica koju imam – i to bez konkurencije."),
    array("name" => "Nikola A.", "text" => "Odlična i za zimu ispod dukserice – zadržava toplinu."),
    array("name" => "Hrvoje E.", "text" => "Naručio sam je zbog preporuka i stvarno nisu bile pretjerane."),
    array("name" => "Andrej J.", "text" => "Stvarno dobra investicija. Odradit će i posao i stil."),
    array("name" => "Damir H.", "text" => "Noriks je pokazao koliko razlika čini dobar kroj. Nema povlačenja u ramenima, rub je ravan i ne diže se. Udobnost 10/10."),
    array("name" => "Blaž P.", "text" => "Sve pohvale."),
    array("name" => "Miro Z.", "text" => "Ima nešto u tom rezu – odmah izgledaš urednije."),
    array("name" => "Filip B.", "text" => "Nikada nisam nosio majicu koja se ovako dobro prilagođava tijelu. Nevjerojatna udobnost."),
    array("name" => "Kristijan E.", "text" => "Noriks tkanina je glatka, ali ne skliska. Na koži je ugodna i ne ostavlja tragove. Odlično podnosi svakodnevno nošenje."),
    array("name" => "Marin D.", "text" => "Ne skuplja dlačice ni prašinu, što mi je ogroman plus."),
    array("name" => "Ivan D.", "text" => "Idealna za svakog tko cijeni udobnost, ali ne želi izgledati opušteno."),
    array("name" => "Krešo N.", "text" => "Nosio sam je cijeli dan na suncu i nije mi bilo vruće. Fantastična tkanina."),
    array("name" => "Mario K.", "text" => "Moderan kroj, ali ne pretjeran."),
    array("name" => "Željko E.", "text" => "Obično sam skeptičan prema recenzijama, ali ovdje je sve točno."),
    array("name" => "Siniša H.", "text" => "Udobna i vizualno čista – ne tražim ništa više."),
    array("name" => "Damjan V.", "text" => "Nosim je za posao, ali i navečer kad idem van. Odličan stil."),
    array("name" => "Božo J.", "text" => "Osvježenje u svijetu majica. Nema glupih logotipa ni natpisa."),
    array("name" => "Daniel K.", "text" => "Noriks je spoj udobnosti i urednog izgleda. Mogu je nositi ispod sakoa bez da izgleda sportski. Preporučujem svima koji vole minimalizam."),
    array("name" => "Jakov P.", "text" => "Odmah sam naručio još dvije."),
    array("name" => "Leon F.", "text" => "Blagi sjaj izgleda elegantno."),
    array("name" => "Gordan J.", "text" => "Obožavam kroj koji prati figuru, a nije neudoban."),
    array("name" => "Vjekoslav R.", "text" => "Dugo nisam bio ovako zadovoljan kupnjom odjeće online."),
    array("name" => "Tihomir B.", "text" => "Savršena stvar za svaki dan. Udobna, jednostavna i kvalitetna."),
    array("name" => "Mislav K.", "text" => "Noriks majica ima odličan osjet na koži. Nema grebanja, nema iritacija, a i nakon više sati izgleda uredno. Veličina je precizna."),
    array("name" => "Andro V.", "text" => "Pouzdana kvaliteta iz tjedna u tjedan. Noriks diše, dobro stoji i ne prozire se. Uzeo sam još dvije boje."),
    array("name" => "Damir C.", "text" => "Nakon nekoliko nošenja mogu potvrditi – vrijedi svake kune."),
    array("name" => "Tomislav N.", "text" => "Noriks preživi i perilicu i sušilicu bez problema."),
    array("name" => "Boris U.", "text" => "Imam je u više boja."),
    array("name" => "Alen T.", "text" => "Prvi dojam? Wow. A drugi? I dalje wow."),
    array("name" => "Stjepan H.", "text" => "Noriks ovratnik ne 'pleše' nakon pranja. Ravan šav i čvrst rub daju uredan izgled. Baš kako treba."),
    array("name" => "Dino E.", "text" => "Jednostavno – najbolja majica koju sam ikad kupio."),
    array("name" => "Ante H.", "text" => "Noriks je točno ono što sam tražio. Jednostavna, čista linija i udobnost koja ne popušta ni nakon dana na poslu."),
    array("name" => "Filip L.", "text" => "Kvaliteta izrade odlična."),
    array("name" => "Kristijan T.", "text" => "Tkanina je lagana ali izdržljiva. Pogodna i za sport."),
    array("name" => "Marijan O.", "text" => "Ovakav osjećaj slobode nisam imao s drugim majicama."),
    array("name" => "Petar B.", "text" => "Super i pri vlažnosti."),
    array("name" => "Fran D.", "text" => "Kupio sam više komada."),
    array("name" => "Nikola M.", "text" => "Rastezljiva i udobna."),
    array("name" => "Ivan R.", "text" => "Noriks je odličan i po ljeti i zimi. Ljeti diše, zimi služi kao top sloj ispod jakne. Svestran i praktičan."),
    array("name" => "Mario F.", "text" => "Izgleda dovoljno profesionalno."),
    array("name" => "Željko C.", "text" => "Izdržava i naporna nošenja."),
    array("name" => "Vlado F.", "text" => "Noriks ne gubi formu ni nakon dosta pranja. Boja ostaje ista, a ovratnik čvrst. Kupujem opet."),
    array("name" => "Ante J.", "text" => "Noriks mi je bolji od većine skupljih brendova koje sam probao. Materijal je ugodan, a kroj elegantan bez napora."),
    array("name" => "Luka V.", "text" => "Za razliku od mnogih majica – ova ostaje čvrsta i nakon dana nošenja."),
    array("name" => "Nikša V.", "text" => "Noriks izgleda kao nov i nakon mjeseci. Nema kuglica ni razvlačenja, a šavovi su i dalje uredni."),
    array("name" => "Kristijan N.", "text" => "Noriks ima odličnu gustoću tkanja. Nije proziran, ali i dalje prozračan. Odličan balans."),
    array("name" => "Božo C.", "text" => "Prvi komad koji je odmah sjeo bez ikakvih dorada."),
    array("name" => "Zdravko U.", "text" => "Noriks je pogodio kroj za moju građu. Rame točno, duljina taman. Ne podvlači se i ne uvija."),
    array("name" => "Mislav S.", "text" => "Dostavljač bio jako ljubazan."), /* kratka neutralna — ostavljeno radi mixa stila */
    array("name" => "Goran J.", "text" => "Noriks se može kombinirati i s tenisicama i s cipelama. Na fotkama izgleda dobro, uživo još bolje. Minimalizam koji traje."),
    array("name" => "Krešimir Y.", "text" => "Svaki put kad je obučem, osjećam se samouvjereno."),
    array("name" => "Vedran F.", "text" => "Savršena majica za svaki dan – to je sve što trebate znati."),
    array("name" => "Davor O.", "text" => "Noriks je lagan, ali drži liniju. U pokretu ne 'leti' i ne lijepi se. Ugodno iznenađenje."),
    array("name" => "Nikola H.", "text" => "Noriks ovratnik ostaje ravan, nema valova ni nakon sušilice. Vidi se kvalitetna konstrukcija."),
    array("name" => "Tihomir G.", "text" => "Odmah znao da ću kupiti opet."),
    array("name" => "Anđelo M.", "text" => "Noriks me oduševio teksturom. Na koži je mekana, ali vizualno djeluje uredno i 'skupo'. Uz traperice izgleda top."),
    array("name" => "Žarko T.", "text" => "Vrlo brza isporuka i odlična koordinacija."), /* kratko neutralno */
    array("name" => "Nikola J.", "text" => "Noriks sjeda u ramenima bez nabora. Rukavi taman dugi, ne uvlače se. Baš pogođeno."),
    array("name" => "Andrija P.", "text" => "Najbolji omjer cijene i kvalitete."),
    array("name" => "Alen J.", "text" => "Majica se nosi kao da je napravljena po mjeri. Izvrsna izrada."),
    array("name" => "Fran E.", "text" => "Boja još bolja uživo."),
    array("name" => "Lovro V.", "text" => "Meka i čvrsta u isto vrijeme."),
    array("name" => "Marin K.", "text" => "Mekana i otporna."),
    array("name" => "Filip T.", "text" => "Nema šavova koji žuljaju. Vrlo ugodno iznenađenje."),
    array("name" => "Sven R.", "text" => "Kupio sam jednu za probu, ali nakon nošenja naručio još tri!"),
    array("name" => "Igor T.", "text" => "Kroj je fantastičan – naglašava ramena i skriva trbuh."),
    array("name" => "Danijel E.", "text" => "Jedna od rijetkih majica koje mi odgovaraju u ramenima i duljini."),
    array("name" => "Ante I.", "text" => "Noriks je nevjerojatno svestran. U teretani prozračan, u uredu dovoljno 'clean'. Teško je to pogoditi, ali uspjeli su."),
    array("name" => "Željko O.", "text" => "Noriks izgleda uredno i nakon više sati sjedenja. Nema onog gužvanja oko struka. Super!"),
    array("name" => "Alen V.", "text" => "Noriks u crnoj izgleda posebno dobro. Boja je duboka i ne blijedi nakon pranja. Uzet ću još sivu."),
    array("name" => "Nikša B.", "text" => "Noriks balansira između casual i smart. Kroj je uredan, a tkanina ugodna. Odlično za svaki dan."),
    array("name" => "Mladen C.", "text" => "Noriks se ne 'peluca' ni nakon više pranja. To mi je veliki plus jer me to najviše nervira kod majica."),
    array("name" => "Mario D.", "text" => "Noriks je stigao i odmah postao favorit u ormaru. Udobnost bez žrtvovanja izgleda."),
    array("name" => "Tomislav R.", "text" => "Noriks se brzo suši i ne ostavlja tragove pegle. Za mene koji putujem često, to je idealno."),
    array("name" => "Zvonimir T.", "text" => "Volim jednostavne komade, a ova majica je upravo to – bez suvišnih detalja."),
    array("name" => "Boris T.", "text" => "Noriks je toliko udoban da ga često zaboravim da nosim. A u ogledalu izgleda uredno i čisto."),
    array("name" => "Željko M.", "text" => "Noriks se pokazao pouzdanim izborom za svaki dan. Drži formu, a ovratnik ne 'bježi'."),
    array("name" => "Dario B.", "text" => "Lagana, neprozirna, udobna. Nema što drugo poželjeti."),
    array("name" => "Ivan T.", "text" => "Noriks u L veličini mi je kao skrojen. Rukavi taman, duljina odlično pokriva."),
    array("name" => "Stanko P.", "text" => "Odličan fit i udobnost. Noriks je pogodak."),
    array("name" => "Petar V.", "text" => "Noriks je najbolja majica u ovom rangu. Ne prozire, ne steže, ne gubi boju."),
    array("name" => "Vjekoslav D.", "text" => "Noriks izgleda uredno i nakon cijelog dana. Bez nabora i uvijanja ovratnika."),
    array("name" => "Nino T.", "text" => "Noriks se ponaša izvrsno i na vrućini. Prozračan i lagan."),
    array("name" => "Željko B.", "text" => "Noriks podiže svaki outfit bez puno truda."),
    array("name" => "Ante V.", "text" => "Noriks ostaje svjež i nakon dugog dana. Materijal očito kvalitetan."),
    array("name" => "Vjekoslav K.", "text" => "Izgled i osjećaj daleko nadilaze cijenu. Apsolutno preporučujem."),
    array("name" => "Davor L.", "text" => "Noriks se odlično ponaša na koži. Nema iritacija ni nakon cijelog dana."),
    array("name" => "Renato K.", "text" => "Noriks kroj je čist i moderan. Ništa viška, sve taman."),
    array("name" => "Darko A.", "text" => "Ne gubi oblik."),
    array("name" => "Mislav G.", "text" => "Noriks je jako zahvalan za kombiniranje. Ide uz traper, chino, pa čak i ispod sakoa."),
    array("name" => "Luka C.", "text" => "Noriks u bijeloj nije proziran. To mi je najvažnije i tu je prošao test."),
    array("name" => "Kristijan O.", "text" => "Noriks rubovi ostaju ravni, nema 'valova'. Izgleda uredno i nakon pranja."),
    array("name" => "Stjepan Z.", "text" => "Noriks XXL mi stoji bolje od mnogih drugih brendova. Krojevi su im pametni."),
    array("name" => "Siniša T.", "text" => "Noriks tkanina diše i kad je vruće. Nema neugodnog osjećaja."),
    array("name" => "Ante M.", "text" => "Noriks je odličan izbor za svakodnevicu. Udoban je i izgleda odlično."),
    array("name" => "Damir N.", "text" => "Kad je obučeš, vidiš da netko misli na detalje. Svaka čast."),
    array("name" => "Jakša R.", "text" => "Noriks je stabilan i nakon sušilice, bez skupljanja. To nisam očekivao."),
    array("name" => "Krešimir W.", "text" => "Lagano strukirana, ali ne steže – top proizvod."),
    array("name" => "Toni F.", "text" => "Kvaliteta na razini premiuma."),
    array("name" => "Vedran R.", "text" => "Noriks mi je ispao top choice. Jednostavan komad koji izgleda 'skupo'."),
    array("name" => "Mario J.", "text" => "Noriks me pozitivno iznenadio debljinom tkanine. Nije pretežak, a ne prozire. Odlično izbalansirano."),
    array("name" => "Ivan B.", "text" => "Noriks mi je došao kao rješenje 'jedna majica za sve'. Ne razmišljam — uzmem i dobro izgleda."),
    array("name" => "Robert E.", "text" => "Noriks rubovi i šavovi su precizni. Nigdje končića, sve uredno."),
    array("name" => "Mladen P.", "text" => "Noriks zadržava svjež izgled i nakon puno nošenja. To me najviše oduševilo."),
    array("name" => "Kristijan Y.", "text" => "Noriks u tamnozelenoj izgleda posebno dobro. Boja 'radi' uz sve."),
    array("name" => "Željko H.", "text" => "Noriks M mi je idealan. Rukavi mrvicu kraći nego kod drugih — sviđa mi se."),
    array("name" => "Filip M.", "text" => "Sve prošlo jednostavno i bez komplikacija."), /* kratko neutralno */
    array("name" => "Tvrtko S.", "text" => "Izgledom podsjeća na premium brendove, ali bez te visoke cijene."),
    array("name" => "Alan J.", "text" => "Kao da je krojena po mjeri."),
    array("name" => "Vladimir C.", "text" => "Stigla brzo, savršeno zapakirana i odmah sam je obukao – oduševljenje!"),
    array("name" => "David I.", "text" => "Savršena za ležerno subotnje jutro, ali i dovoljno elegantna za večeru."),
    array("name" => "Karlo M.", "text" => "Imam osjetljivu kožu i ova majica mi savršeno odgovara – bez iritacija."),
    array("name" => "Franjo P.", "text" => "Nakon cijelog dana nošenja nema neugodnog mirisa. Vrlo prozračna."),
    array("name" => "Zoran L.", "text" => "Noriks kroj skriva trbuh i širi ramena. Odlična optika."),
    array("name" => "Davor I.", "text" => "Noriks mi je praktičan i na poslu i doma. Jedan komad, puno situacija."),
    array("name" => "Igor S.", "text" => "Vrlo jednostavan proces narudžbe, sve jasno i pregledno."), /* kratko neutralno */
    array("name" => "Ante D.", "text" => "Noriks u bijeloj i tamnoplavoj — savršena kombinacija. Idem po treću."),
    array("name" => "Andrej K.", "text" => "Osjećam se samopouzdanije u njoj."),
    array("name" => "Mislav N.", "text" => "Noriks nakon sušenja ostaje ravan, bez dodatnog peglanja. Za mene game-changer."),
    array("name" => "Goran P.", "text" => "Noriks šavovi su mekani iznutra — nema grebanja."),
    array("name" => "Željko D.", "text" => "Noriks je moj go-to za ured uz sako i traper."),
    array("name" => "Ivan G.", "text" => "Noriks tkanina se ne 'skida' i ne 'peluca'. Kvaliteta."),
    array("name" => "Leo C.", "text" => "Boja je točno kao na fotografiji – bez iznenađenja."),
    array("name" => "Damjan P.", "text" => "Dojam je kao da nosiš puno skuplji komad odjeće."),
    array("name" => "Ervin S.", "text" => "Noriks me ugodno iznenadio već na dodir. Mekano, ali čvrsto."),
    array("name" => "Srećko G.", "text" => "Usluga odlična, dostavljač bio vrlo profesionalan."), /* kratko neutralno */
    array("name" => "Vjeko M.", "text" => "Noriks je izdržljiv i nakon intenzivnog nošenja. Šavovi su ko novi."),
    array("name" => "Nikola V.", "text" => "Noriks tkanina je zahvalna — nema fleka ni nakon cijelog dana."),
    array("name" => "Stjepan O.", "text" => "Noriks u XL mi stoji točno kako treba. Nema viška tkanine."),
    array("name" => "Borna R.", "text" => "Noriks je pun pogodak za one koji vole čiste linije."),
    array("name" => "Ante Š.", "text" => "Noriks me prati od teretane do kavane. Svestran komad."),
    array("name" => "Mislav P.", "text" => "Noriks u sivoj izgleda jako profinjeno. Minimalizam koji traje."),
    array("name" => "Filip G.", "text" => "Noriks je udoban i na dužim putovanjima. Nema znojenja."),
    array("name" => "Ivan Y.", "text" => "Noriks je moja preporuka svima koji hoće dobar osnovni komad."),
    array("name" => "Karlo P.", "text" => "Noriks drži formu i kad ga nosim ispod košulje."),
    array("name" => "Matej D.", "text" => "Idealna za ljude koji žele izgledati dobro bez puno truda."),
    array("name" => "Emil C.", "text" => "Jednostavno je savršena. Uzeo sam sve dostupne boje.")
);
?>
