<?php
/**
 * Slovak product reviews for NORIKS t-shirts
 */

$auto_reviews_en = array(
    array("name" => "Marek K.", "text" => "Veľmi pohodlné tričko. Už som si objednal ďalšie. Hodí sa takmer ku všetkému."),
    array("name" => "Tomáš H.", "text" => "Strih NORIKS trička je naozaj vydarený. Sleduje líniu tela, ale nesťahuje ani v ramenách, ani okolo pása. Ani po praní sa nekrúti."),
    array("name" => "Peter S.", "text" => "Kúpil som jedno a hneď som objednal ďalšie tri rôznych farieb. Skvelý výber."),
    array("name" => "Jakub P.", "text" => "Hneď som si objednal ďalšie dve."),
    array("name" => "Martin R.", "text" => "Kúpil som jedno na skúšku, ale po nosení som objednal ďalšie tri!"),
    array("name" => "Štefan G.", "text" => "Služba vynikajúca, kuriér bol veľmi profesionálny."),
    array("name" => "Andrej M.", "text" => "NORIKS tričká sú ideálne na prácu aj na tréning – iné značky už nekupujem."),
    array("name" => "Lukáš B.", "text" => "Materiál je mäkký a príjemný na pokožku. Veľmi spokojný."),
    array("name" => "Filip D.", "text" => "Konečne tričko, ktoré mi dobre sedí. Strih je perfektný."),
    array("name" => "Ján V.", "text" => "Kvalita je na prvý pohľad viditeľná. Odporúčam každému."),
    array("name" => "Michal K.", "text" => "Nosím ho každý deň a stále vyzerá ako nové."),
    array("name" => "Ondrej L.", "text" => "Tričko nestráca tvar ani po mnohých praniach."),
    array("name" => "Daniel P.", "text" => "Skvelý strih pre väčšiu postavu. Konečne niečo, čo mi sadne."),
    array("name" => "Rastislav J.", "text" => "Objednal som pre celú rodinu. Všetci sú spokojní."),
    array("name" => "Branislav T.", "text" => "Najlepšie tričko, aké som kedy mal. Materiál je prémiový."),
    array("name" => "Roman F.", "text" => "Rýchle doručenie a skvelá kvalita. Určite budem nakupovať znova."),
    array("name" => "Vladimír N.", "text" => "Strih je presne taký, aký som hľadal. Perfektné."),
    array("name" => "Pavol H.", "text" => "Tričko je priedušné a pohodlné aj v lete."),
    array("name" => "Erik S.", "text" => "Kvalita za rozumnú cenu. Som veľmi spokojný."),
    array("name" => "Juraj B.", "text" => "Materiál je prvotriedny. Odporúčam."),
    array("name" => "Samuel C.", "text" => "Nosím NORIKS tričká už rok a stále vyzerajú skvele."),
    array("name" => "Patrik M.", "text" => "Strih je pohodlný a moderne vyzerá."),
    array("name" => "Viktor K.", "text" => "Kúpil som čierne aj biele. Obe sú perfektné."),
    array("name" => "Adam R.", "text" => "Tričko nesedá a nesťahuje. Presne to, čo som potreboval."),
    array("name" => "Matúš P.", "text" => "Kvalita materiálu je vynikajúca. Určite si objednám viac."),
    array("name" => "Dávid L.", "text" => "Skvelá voľba pre každodenné nosenie."),
    array("name" => "Boris V.", "text" => "Tričko je ľahké a priedušné. Super na leto."),
    array("name" => "Tibor H.", "text" => "Materiál je mäkký ako maslo. Milujem to."),
    array("name" => "Oliver J.", "text" => "Strih je presný a tričko dobre sedí."),
    array("name" => "Karol D.", "text" => "Najlepšie tričko v mojom šatníku."),
    array("name" => "Marián S.", "text" => "Kvalita je na vysokej úrovni. Odporúčam."),
    array("name" => "Róbert K.", "text" => "Nosím to denne a som veľmi spokojný."),
    array("name" => "Milan T.", "text" => "Strih sedí perfektne na mojej postave."),
    array("name" => "Jozef N.", "text" => "Materiál je príjemný a neškriabe."),
    array("name" => "Stanislav B.", "text" => "Tričko nestráca farbu ani po mnohých praniach."),
    array("name" => "Richard F.", "text" => "Skvelá kúpa. Veľmi spokojný zákazník."),
    array("name" => "Dominik P.", "text" => "Kvalita zodpovedá cene. Odporúčam."),
    array("name" => "Jaroslav M.", "text" => "Nosím NORIKS a už iné nechcem."),
    array("name" => "Adrián L.", "text" => "Tričko je pohodlné celý deň."),
    array("name" => "Marcel K.", "text" => "Strih je moderný a dobre vyzerá."),
);
