<?php
/**
 * Slovak boxerky reviews for NORIKS
 */

$auto_reviews_en = array(
    array("name" => "Róbert P.", "text" => "NORIKS boxerky ma naozaj prekvapili. Tkanina je mäkká, neškriabe a nesťahuje tam, kde nemá."),
    array("name" => "Marek S.", "text" => "Naozaj pohodlné boxerky na celý deň, necítim ich na sebe."),
    array("name" => "Miroslav L.", "text" => "NORIKS boxerky vyzerajú kvalitne hneď, ako ich chytíte do ruky. Všetka česť."),
    array("name" => "Nikola R.", "text" => "NORIKS boxerky sa mi stali prvou voľbou v zásuvke, vždy ich vyberiem ako prvé."),
    array("name" => "Andrej M.", "text" => "NORIKS boxerky sú ideálne na prácu aj na tréning – iné značky už nekupujem."),
    array("name" => "Vojtech H.", "text" => "NORIKS boxerky netlačia ani pri dlhom sedení v kancelárii."),
    array("name" => "Štefan C.", "text" => "Kúpil som jeden pár, potom som hneď objednal ďalšie tri. To hovorí za všetko."),
    array("name" => "Gustáv B.", "text" => "NORIKS boxerky mi nahradili všetky staré, ostatné som vyhodil zo skrine."),
    array("name" => "Nino E.", "text" => "NORIKS boxerky držia všetko na mieste aj počas tréningu."),
    array("name" => "Boris R.", "text" => "NORIKS boxerky sú také pohodlné, že ich takmer necítim."),
    array("name" => "Dušan K.", "text" => "Prvé boxerky, s ktorými nemám problém so zdvíhaním nohavíc."),
    array("name" => "Marián J.", "text" => "NORIKS boxerky nestrácajú tvar ani po mesiaci prania."),
    array("name" => "Andrej K.", "text" => "S týmito boxerkami už nerozmýšľam, čo si obliecť dole – všetko ostatné je horšie."),
    array("name" => "Zdenko L.", "text" => "Toto sú moje najpohodlnejšie boxerky doteraz, bez preháňania."),
    array("name" => "Viktor P.", "text" => "NORIKS boxerky majú správnu dĺžku, nerežú v slabinách."),
    array("name" => "Lukáš F.", "text" => "Vynikajúce boxerky na každý deň – už nerozmýšľam o iných."),
    array("name" => "Anton C.", "text" => "NORIKS boxerky ma príjemne prekvapili – pohodlie 10/10."),
    array("name" => "Vojto J.", "text" => "NORIKS boxerky nerežú ani v páse, ani na stehnách."),
    array("name" => "Dórian S.", "text" => "NORIKS boxerky nie je vidieť cez tenké nohavice, čo je pre mňa veľmi dôležité."),
    array("name" => "René H.", "text" => "Cítim sa oveľa pohodlnejšie počas dňa, odkedy nosím tieto boxerky."),
    array("name" => "Tomáš E.", "text" => "NORIKS boxerky zvládnu prácu aj tréning bez problémov."),
    array("name" => "Iľja S.", "text" => "NORIKS boxerky netlačia v slabinách, čo bol vždy môj problém pri iných."),
    array("name" => "Želimír K.", "text" => "Nepíšem často recenzie, ale tieto boxerky si to zaslúžia."),
    array("name" => "Anton Ž.", "text" => "NORIKS boxerky posúvajú úroveň pohodlia na úplne novú úroveň."),
    array("name" => "Augustín J.", "text" => "NORIKS boxerky sa mi stali prvou voľbou."),
    array("name" => "Benedikt K.", "text" => "Konečne boxerky, ktoré nesťahujú."),
    array("name" => "Teo Z.", "text" => "Toto sú jediné boxerky, ktoré chcem nosiť."),
    array("name" => "Damián K.", "text" => "Najlepšie boxerky, aké som kúpil."),
    array("name" => "Bono K.", "text" => "Nevedel som, že boxerky môžu byť také dobré."),
    array("name" => "Viliam P.", "text" => "Najlepšie boxerky pre moju postavu."),
    array("name" => "Dário S.", "text" => "Naozaj vynikajúce boxerky."),
    array("name" => "Alan F.", "text" => "Tieto boxerky sú game-changer."),
    array("name" => "Lukáš R.", "text" => "Konečne boxerky, ktoré sedia ako majú."),
    array("name" => "Peter M.", "text" => "Kvalita je na vysokej úrovni. Odporúčam."),
    array("name" => "Ján K.", "text" => "Pohodlné a priedušné. Presne to, čo som hľadal."),
    array("name" => "Michal B.", "text" => "Materiál je prvotriedny. Skvelá kúpa."),
    array("name" => "Ondrej T.", "text" => "Nosím ich každý deň a som nadmieru spokojný."),
    array("name" => "Daniel H.", "text" => "Strih je perfektný pre väčšiu postavu."),
    array("name" => "Filip V.", "text" => "Už iné boxerky nechcem. Len NORIKS."),
    array("name" => "Martin D.", "text" => "Kvalita za rozumnú cenu. Veľmi spokojný."),
);
